name: Check for broken links

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  broken-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Check for broken links
        run: ./scripts/broken-links.sh
